[DATA]
data_set = "https://raw.githubusercontent.com/5x12/ml-cookbook/master/supplements/data/heart.csv"
target = 'target'


[MODEL]
dt_conf = "model/conf/RF.pkl"
dt_conf_2 = "model/conf/GB.pkl"

[PREDICTION]
VALUES = [42,0,2,120,209,0,1,175,0,0,1,0,2]
